### ISSUE TITLE
如何指定IP和端口

### ISSUE THREAD

**Issue by zyjia** [storyicon/golang-proxy#1]
机器运行在Linux上，只能本地打开，别的机器就无法使用，建议加一个配置IP和PORT的参数。

**Comment by hojit** [comment]
你要看源码
`address := fmt.Sprintf("localhost:%d", ServiceListenPort)
	log.Infof("[S]Start Service on %s", address)
	http.ListenAndServe(address, router)`
这里host被指定死为localhost,port在const.go里面配置成了9999。
你可以自己动手修改重新编译的。总想着拿来主义呀，不好

**Comment by storyicon** [comment]
I'm sorry to reply to you now, but I guess what you're describing is that you want to run distributed across multiple containers. Now you can have multiple `golang-proxy` connections to the same `MySQL` database.                   
I took your advice into account when developing [`v3.0`](https://github.com/storyicon/golang-proxy). Now you can specify that `golang-proxy` uses `MySQL` databases instead of portable `SQLite` by adding `config.yml` to the `root directory of golang-proxy`.              
More information: [`Config`](https://github.com/storyicon/golang-proxy/tree/master/config)
