### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by ghost** [storyicon/golang-proxy#3]
func StartProducer() {

	scheduler := cron.New()

	sources := dao.GetSources()

	log.Infof("[Producer]Totally %d source was found", len(sources))

	std.Dump(sources)

	for _, source := range sources {

		(func(scheduler *cron.Cron, source *model.Source) {

			go newSourceCrawler(source)

			name := source.Name

			interval := source.Category.Interval

			log.Infof("[Producer]Periodical Task %s Was Assigned %s", name, interval)

			scheduler.AddFunc(interval, func() {

				log.Infof("[Producer]Periodical Task @%s is Running!", name)

				newSourceCrawler(source)

			})

		})(scheduler, source)

	}

	scheduler.Start()

}

这个任务管理器中，怎么要调用两次?

**Comment by storyicon** [comment]
Hello, this is to make the `newSourceCrawler` method execute immediately, instead of waiting for the time specified by `interval`.
```go
package main

import (
	"log"

	"github.com/robfig/cron"
)

func workhorse() {
	log.Println("I AM DOING SOMETHING!")
}

func main() {
	log.Println("Start")
	scheduler := cron.New()
	scheduler.AddFunc("@every 1m", func() {
		workhorse()
	})
	go workhorse()
	scheduler.Run()
}
```
In the above example, if you delete `go workhorse()`, you will see `Start` first, and you need to wait a minute before you can see `I AM DOING SOMETHING!`.

Sorry, this is an ugly piece of code I wrote in my spare time, and I will refactor it in the near future.
