### ISSUE TITLE
开箱即用报错

### ISSUE THREAD

**Issue by zoooozz** [storyicon/golang-proxy#6]
Error 1305: FUNCTION proxy.RANDOM does not exist"

**Comment by storyicon** [comment]
Sorry, I am late. How can I reproduce this mistake? 
①If you're using [binary files here](https://github.com/storyicon/golang-proxy/releases)
In theory, this kind of error will not occur. Because "the function does not exist" will be thrown at compile time.
②If you compile it yourself
I just pulled the code from master branch and compiled it successfully.

I need more information.

**Comment by assoyuan** [comment]
> ①If you're using [binary files here](https://github.com/storyicon/golang-proxy/releases)
> In theory, this kind of error will not occur. Because "the function does not exist" will be thrown at compile time.

Download the base file, after executing, visit "localhost: 9999 / random" in the browser and report the error:
{"error": "Error 1305: FUNCTION proxy.RANDOM does not exist", "message": []}

**Comment by storyicon** [comment]
Apologize for my late arrival. I just fixed this problem.
Duplicate of #7
